### ISSUE TITLE
API Cient Examples in astronomy/net/client/examples Do Not Work

### ISSUE THREAD

**Issue by exowanderer** [dstndstn/astrometry.net#146]
I am trying to use the astrometry.net API to examine a stack of new images. Using the website one at a time for 100+ images is too much button pushing. 

I cloned the github repo, installed the code, and downloaded catalogue files; but the solutions are wrong: the WCS is no where near the actual RA and Dec of the field; this results in a blank image subtraction because the reference frame is being "projected" out of view. 

So I had to start using the website directly and came across the API.

----
Unfortunately, the API is not working for 2 independent reasons:

(1) the python package does not include `astrometry.net.client`. That is, if I follow the example `apod.py` then the following error is generated:

```python
Traceback (most recent call last):
  File "examples/apod.py", line 14, in <module>
    from astrometry.net.client import Client
ModuleNotFoundError: No module named 'astrometry.net'
```

(2) If I try to run the client.py from the bash terminal, using the `examples/rc3.sh` example, the following error is flagged:

python $HOME/path/to/github/astrometry.net/net/client/client.py \
    --server http://staging.astrometry.net/api/ \
    --apikey MY_APIKEY  \
    --upload $HOME/path/to/fits_filename.fits

```bash    
Running with args ['$HOME/path/to/github/astrometry.net/net/client/client.py', '--server', 'http://staging.astrometry.net/api/', '--apikey', 'MY_APIKEY', '--upload', '$HOME/path/to/fits_filename.fits']
Python: {'apikey': 'MY_APIKEY'}
Sending json: {"apikey": "MY_APIKEY"}
Sending to URL: http://staging.astrometry.net/api/login
Sending form data: {'request-json': '{"apikey": "MY_APIKEY"}'}
Sending data: b'request-json=%7B%22apikey%22%3A+%22MY_APIKEY%22%7D'
HTTPError HTTP Error 404: Not Found
Wrote error text to err.html
Traceback (most recent call last):
  File "$HOME/path/to/github/astrometry.net/net/client/client.py", line 353, in <module>
    c.login(opt.apikey)
  File "$HOME/path/to/github/astrometry.net/net/client/client.py", line 147, in login
    sess = result.get('session')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by exowanderer** [comment]
That was incredibly helpful; thank you!

I'll submit a new issue for the false positives. I have 20-25% of my images result in false positives. My team is right now reanalyzing those with the updated github (old version circa February 2018).  I'll let you know if we get the same errors. Note: It is currently "still processing" after far too long.

I'll put all that in a different issue.
