### ISSUE TITLE
Astrometry_net - images failing to solve

### ISSUE THREAD

**Issue by awesomecosmos** [dstndstn/astrometry.net#230]
I am writing code using Python's astroquery.astrometry_net package, and am attempting to use ast.solve_from_image from a test list of 4 FITS images, 2 with exposure length 60s, and 2 with exposure length 300s. I have found that all but one image fails to solve, and they each return the following error:

```
Traceback (most recent call last):

  File "C:\Users\ave41\OneDrive - University of Canterbury\Master's 2021\ASTR480 Research\ASTR480 Code\01 Data Reduction Pipeline\DataReductionPipeline\src\asp.py", line 93, in <module>
    test_wcs_header = ast.solve_from_image(another_test_img3,solve_timeout=1000,

  File "C:\Users\ave41\Anaconda3\lib\site-packages\astroquery\astrometry_net\core.py", line 406, in solve_from_image
    return self.solve_from_source_list(sources['xcentroid'],

  File "C:\Users\ave41\Anaconda3\lib\site-packages\astroquery\astrometry_net\core.py", line 305, in solve_from_source_list
    return self.monitor_submission(submission_id,

  File "C:\Users\ave41\Anaconda3\lib\site-packages\astroquery\astrometry_net\core.py", line 255, in monitor_submission
    raise TimeoutError('Solve timed out without success or failure',

TimeoutError: ('Solve timed out without success or failure', 4857551)
```
For the image that does work, it is the first file in the directory, and it returns a WCS header as expected, and when I check on the astrometry.net page, it has solved successfully (http://nova.astrometry.net/status/4857455). However, the other three images return the error above, and when I check on astrometry.net at the time when the above error is returned, it says the job is queued, and after 5-10 minutes, fails to solve on the website too. Example of a failed solve: http://nova.astrometry.net/status/4857501

I have set a timeout of 1000 seconds in my code (https://github.com/awesomecosmos/Data-Reduction-Pipeline/blob/main/src/asp.py), and yet the images fail to solve within 3 minutes of running the program. I cannot find any more documentation on how to solve this error. Please can someone point me in the right direction?

**Comment by dstndstn** [comment]
Hi,

Could you please attach (or upload to nova.astrometry.net one of the FITS *images* (not just the detected star positions)?  Or, check yourself whether the detected star positions are reasonable, complete, and correct.

Also, as others have said, if you are setting the RA,Dec, pixel scale, or other parameters, ensure that they are correct.  And anything else you can tell us about the image (camera, etc) will be helpful.

**Comment by dstndstn** [comment]
No reply.  Closing.
