### ISSUE TITLE
solve-field CLI fails

### ISSUE THREAD

**Issue by Banjoman02** [dstndstn/astrometry.net#322]
Encountering an error now every time I try running `solve-field`.

`(odl) mcampbell02@1311-mcampbell:~/projects/ressolve$ solve-field examples/M42_00001.fits 
Reading input file 1 of 1: "examples/M42_00001.fits"...
/usr/bin/python3: Error while finding module specification for 'astrometry.util.image2pnm' (ModuleNotFoundError: No module named 'astrometry.util')
augment-xylist.c:591:backtick Failed to run command: /usr/bin/python3 -m astrometry.util.image2pnm --infile examples/M42_00001.fits --uncompressed-outfile /tmp/tmp.uncompressed.FFRPrT --outfile /tmp/tmp.ppm.Ox7oDF --ppm --mydir /usr/bin/solve-field
 ioutils.c:568:run_command_get_outputs Command failed: return value 1`

Attempted uninstalling and reinstalling astrometry.net packing with apt.

**Comment by dstndstn** [comment]
Hi,

Usually this sort of thing happens when you have a partially-removed old install and a new one in a different path.

The code runs the "image2pnm" program, which should be a script that runs the python module astrometry.util.image2pnm (setting the PYTHONPATH to a relative path)

It's hard to diagnose the problem exactly, but you can try finding out things like

```
which image2pnm
image2pnm
dpkg -L astrometry.net
apt search astrometry.net
python3 -c "import astrometry; print(astrometry.__file__)"
python3 -c "import astrometry.util as x; print(x.__file__)"
```

**Comment by dstndstn** [comment]
Eg, here's a similar report that was due to an old partial installation
https://groups.google.com/g/astrometry/c/APd4zYDaOgs/m/2dMy3YKvBQAJ

**Comment by blackhaz** [comment]
I am having a similar issue. Running FreeBSD 14.2 and astrometry-0.97_1 from the official FreeBSD repo. Getting:

`% solve-field 55841-S001-R001-C001-Empty-041700.fts
Reading input file 1 of 1: "55841-S001-R001-C001-Empty-041700.fts"...
Running command: /usr/local/bin/image2pnm --infile 55841-S001-R001-C001-Empty-041700.fts --uncompressed-outfile /tmp/tmp.uncompressed.3zNiz0 --outfile /tmp/tmp.ppm.NWJtaG --ppm --mydir /usr/local/bin/solve-field
Command failed: /usr/local/bin/an-fitstopnm -i 55841-S001-R001-C001-Empty-041700.fts > /tmp/tmpab57h8ij.pnm
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/astrometry/util/image2pnm.py", line 298, in main
    convert_image(options.infile, options.outfile,
  File "/usr/local/lib/python3.11/astrometry/util/image2pnm.py", line 235, in convert_image
    (imgtype, errstr) = image2pnm(infile, outfile, force_ppm=force_ppm,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/astrometry/util/image2pnm.py", line 200, in image2pnm
    do_command(cmd % (shell_escape(infile), shell_escape(outfile)))
  File "/usr/local/lib/python3.11/astrometry/util/image2pnm.py", line 60, in do_command
    sys.exit(-1)
SystemExit: -1
augment-xylist.c:591:backtick Failed to run command: /usr/local/bin/image2pnm --infile 55841-S001-R001-C001-Empty-041700.fts --uncompressed-outfile /tmp/tmp.uncompressed.3zNiz0 --outfile /tmp/tmp.ppm.NWJtaG --ppm --mydir /usr/local/bin/solve-field
 ioutils.c:568:run_command_get_outputs Command failed: return value 255
`
Only one astrometry packge is installed. Everything was working fine previously before upgrading the package. I would sincerely appreciate any pointers.

**Comment by dstndstn** [comment]
It was probably compiled with overly aggressive optimization flags that use some processor feature that the build computer has but your doesn't.  If you got this from the official FreeBSD channels you might want to report this issue there so they can fix their build recipe.  Feel free to send them here.
They probably want to set ARCH_FLAGS="" to prevent the Makefile (util/makefile.common) from using something aggressive like -march.
